### PR TITLE
1st commit

### PR DESCRIPTION
**Pull request by mujeeb100**

### CODE REVIEW

**Review by webCatDev — APPROVED** [review]

**Review by zaidansari42 — APPROVED** [review]
Nice !

**Review by syedabdullahali — COMMENTED** [review]
Awesome

**Comment by syedabdullahali** [comment]
Rgba(133,122,200) ?
output

**Review by syedabdullahali — APPROVED** [review]

**Review by Rehan-Khan-Engineer — APPROVED** [review]

**Comment by mujeeb100** [comment]
> Rgba(133,122,200) ?
its color of #857ac8 Color Hex

**Pull request closed without merging**
